//HintName: Tests.Templates+TEMPLATEAttribute.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Tests
{
    internal partial class Templates
    {
        [AttributeUsage(AttributeTargets.Class)]
        private class TEMPLATEAttribute : System.Attribute
        {
            public TEMPLATEAttribute(object arg0)
            {
            }
        }
    }
}
